# Generated by Django 3.0.6 on 2020-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200613_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
