# Generated by Django 3.0.6 on 2020-06-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_order_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
