# Generated by Django 3.0.6 on 2020-06-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
    ]
