# Generated by Django 3.0.6 on 2020-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200620_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('s', 'shirt'), ('t', 't-shirt'), ('j', 'jeans')], max_length=1),
        ),
    ]
